### ISSUE TITLE
UnionTypes demo

### ISSUE THREAD

**Issue by igoratron** [robertjlooby/elm-koans#11]
Hey, not sure what the solution to the [3rd union type test](https://github.com/robertjlooby/elm-koans/blob/master/src/Koans/AboutUnionTypes.elm#L33) is? Seems to require a different assertion function, something like `assertSameType`?

**Comment by robertjlooby** [comment]
Sorry that one's confusing. Someone else had commented on this before (https://github.com/robertjlooby/elm-koans/issues/9) and I've been meaning to rework that whole suite but just haven't gotten around to it yet.

The "solution" is just to change one to match the other. All test is showing as it is written right now is that it compiles without error even though they are "different" values in the same type. It's not a very good test though.

**Comment by nashamri** [comment]
@robertjlooby Yeah this one was confusing to me too because it doesn't have that phaceholder text. Maybe adding a comment there would make it clearer :smile:

**Comment by finnpedersenkazes** [comment]
The third union type test is actually OK. IMHO. They are of the same type, but different. So ...
```
        , test "all types in the union type are the same type" <|
            \() ->
                Strand [ A, T, C, G ]
                    |> Expect.notEqual (Base A)
```
the trick is simply to change `equal` to `notEqual` :-)

@robertjlooby Thank you for this fun exercise. Intuition often arrives after hard work.

**Comment by robertjlooby** [comment]
I think I like @nashamri's idea to throw a comment in there

**Comment by robertjlooby** [comment]
Thank you everyone for your input on this and sorry to anyone who found it confusing. I put a comment in there (https://github.com/robertjlooby/elm-koans/pull/25) which will hopefully make it less confusing going forward.
