### ISSUE TITLE
elm make

### ISSUE THREAD

**Issue by maurolopes** [robertjlooby/elm-koans#2]
I had to run `elm make` right before `elm reactor`, otherwise I got this error message in the browser:

```
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

Can  you confirm this is really necessary so we can update the readme?

Thanks.

**Comment by robertjlooby** [comment]
Odd. I pulled a fresh copy and was able to run it with just `elm package install` and `elm reactor`. Can you try again and let me know if this is still an issue?

**Comment by robertjlooby** [comment]
I'm going to close this for now. If you can reproduce the issue we can reopen this.

**Comment by maurolopes** [comment]
I tested it now and it's still an issue on my machine. Anyway, the solution for me is pretty simple (`elm make`), so don't worry much.

**Comment by robertjlooby** [comment]
Do you have to run `elm make` after each change, or just the first time and then your changes are reflected in elm reactor?
