### ISSUE TITLE
Suggestion : add link to elm-live in README.md

### ISSUE THREAD

**Issue by mlevesquedion** [robertjlooby/elm-koans#27]
Thank you for the koans! A suggestion : add a link to [elm-live](https://github.com/architectcodes/elm-live) in the README. Using elm-live makes for a much more fluid experience thanks to the automatic reloading.

**Comment by robertjlooby** [comment]
Thank you for the suggestion @mlevesquedion! I just updated the README in https://github.com/robertjlooby/elm-koans/commit/8c1785d4a4a1fd6d45815fa9818e6a715c7070c4.
