### ISSUE TITLE
scroll to bottom on page load

### ISSUE THREAD

**Issue by chapmanjacobd** [robertjlooby/elm-koans#30]
I think it would be nice if the page scrolled to the bottom when it loaded.

`window.scrollTo(0,document.body.scrollHeight);`

but not sure how to do this in elm

**Comment by kofigumbs** [comment]
Great idea! I just opened a PR that implements that. If you're curious about how it would look in Elm, it's on [these lines](https://github.com/robertjlooby/elm-koans/pull/31/files#diff-f1ab166876eeb993a8f1f1d6a7a1c37dR42-R44).

**Comment by robertjlooby** [comment]
Thank you for the suggestion @chapmanjacobd and @hkgumbs for implementing it! Hope you enjoyed the koans.
