### ISSUE TITLE
Test "month gets the month"

### ISSUE THREAD

**Issue by joshy** [robertjlooby/elm-koans#4]
Hi Robert,

the test  "month gets the month" is initially already green. I don't know why but I guess it should initially fail.

Cheers,
Joshy

**Comment by robertjlooby** [comment]
Whoops! I get `Expected: Jan; got: Dec` but I guess depending on your timezone the unix epoch could be in January. I fixed it in https://github.com/robertjlooby/elm-koans/commit/43341c3d476c98a3127bf800ec1707e6ae33c8cd. Thank you!
